apiVersion: v2
name: nvidia-gpu-exporter
description: DEPRECATED - the chart moved to the application repository, see https://github.com/utkuozdemir/nvidia_gpu_exporter
type: application
deprecated: true
version: 1.0.1
appVersion: 1.2.1
home: https://github.com/utkuozdemir/nvidia_gpu_exporter
keywords:
  - nvidia
  - gpu
  - exporter
  - nvidia-smi
  - nvidia-gpu-exporter
  - prometheus
sources:
  - https://github.com/utkuozdemir/helm-charts
icon: https://utkuozdemir.org/helm-charts/nvidia.png
maintainers:
  - name: Utku Özdemir
    email: utkuozdemir@gmail.com
    url: https://utkuozdemir.org
annotations:
  artifacthub.io/license: MIT
  artifacthub.io/changes: |
    - Deprecate the chart, it moved to the application repository
  artifacthub.io/images: |
    - name: utkuozdemir/nvidia_gpu_exporter
      image: docker.io/utkuozdemir/nvidia_gpu_exporter:1.2.1
