{{- if .Values.podSecurityPolicy.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "dontstarvetogether.fullname" . }}
  labels:
    {{- include "dontstarvetogether.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "dontstarvetogether.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "dontstarvetogether.fullname" . }}
{{- end }}
